[package]
name = "tetris-rs"
version = "0.0.1"
authors = ["Byron Batteson <byronbatteson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3"
